# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: ankane/pgvector:v0.4.1
    environment:
      # db admin creds - managed by pg image
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin_pw

      # details for an embeddings db, schema, user
      embed_user: embed_usr
      embed_user_pw: ilovellms
      embed_db_name: embed_db
      embed_schema_name: embed_schema

    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data
      - type: bind
        source: ./pginit
        target: /docker-entrypoint-initdb.d