# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: ankane/pgvector:v0.4.1
    environment:
      POSTGRES_PASSWORD: gov_embed

    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data
      - type: bind
        source: ./pginit
        target: /docker-entrypoint-initdb.d