"""Add updated_at key to embeddings table

Revision ID: b3207e0b4a81
Revises: 
Create Date: 2023-05-11 11:21:53.344809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3207e0b4a81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('embeddings_link_fkey', 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'pages', ['link'], ['link'], source_schema='embed_schema', referent_schema='embed_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'embeddings', schema='embed_schema', type_='foreignkey')
    op.create_foreign_key('embeddings_link_fkey', 'embeddings', 'pages', ['link'], ['link'])
    op.drop_column('embeddings', 'updated_at')
    # ### end Alembic commands ###
